# docker-compose.yml
version: '3.8'
services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoring
      - "6222:6222"   # route
    command: [
      "-js",                         # enable JetStream
      "-sd", "/data/jetstream",     # store directory
      "--http_port", "8222"
    ]
    volumes:
      - nats_data:/data
volumes:
  nats_data:
