# docker-compose.yml
version: '3.8'
services:
  nats:
    build: .
    container_name: nats
    restart: unless-stopped
    ports:
      - "42221:4222" # Client connections
      - "82221:8222" # HTTP monitoring
    command: [
      "-js",                         # Enable JetStream
      "-DV",                         # Enable debug & trace
      "--store_dir", "/data/jetstream",
      "--http_port", "82221"
    ]
    volumes:
      - nats_data:/data

volumes:
  nats_data:
