version: "3.8"
services:
  nats:
    build: .
    ports:
      - "4222:4222"   # NATS clients
      - "8222:8222"   # Monitoring
      - "6222:6222"   # Cluster
    command: >
      -js
      -m 8222
